version: '3' # 表示该 Docker-Compose 文件使用的是 Version 2 file
services:
  eureka1:  # 指定服务名称
    restart: always
    build: ./sjloauth2-eureka  # 指定 Dockerfile 所在路径
    ports:    # 指定端口映射
      - "8761:8761"
    environment:
      - EUREKA_SERVER_HOST=192.168.1.180
      - EUREKA_SERVER_PORT=8761
      - IP_ADDRESS=192.168.1.180
